AdminUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AdminUI.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AdminUI.Models;
using Amazon.DeviceFarm.Model;
using Amazon.DirectConnect.Model;
using Microsoft.AspNet.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;


namespace AdminUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly TimesheetContext _Tcontext;
        private readonly LockTableContext _Lcontext;

        public HomeController(ILogger<HomeController> logger, TimesheetContext Tcontext, LockTableContext Lcontext)
        {
            _Tcontext = Tcontext;
            _logger = logger;
            _Lcontext = Lcontext;
        }

        public IActionResult Index(string sortOrder, string pName, string cName, string dateFrom, string dateTo, string prime, string id, string providerId)
        {
            var sheets = GetSheets();

            var model = new HomeModel();
            
            //filter the timesheets 
            if (!string.IsNullOrEmpty(pName))
            {
                model.PName = pName;
                sheets = sheets.Where(t => t.ProviderName.ToLower().Contains(pName.ToLower()));
            }
            if (!string.IsNullOrEmpty(providerId))
            {
                model.ProviderId = providerId;
                sheets = sheets.Where(t => t.ProviderID.ToLower().Contains(providerId.ToLower()));
            }

            if (!string.IsNullOrEmpty(cName))
            {
                model.CName = cName;
                sheets = sheets.Where(t => t.ClientName.ToLower().Contains(cName.ToLower()));
            }
            if (!string.IsNullOrEmpty(prime))
            {
                model.Prime = prime;
                sheets = sheets.Where(t => t.ClientPrime.ToLower().Contains(prime.ToLower()));
            }
            if (!string.IsNullOrEmpty(dateFrom))
            {
                model.DateFrom = dateFrom;
                sheets = sheets.Where(t => t.Submitted >= DateTime.Parse(dateFrom));
            }
            if (!string.IsNullOrEmpty(dateTo))
            {
                model.DateTo = dateTo;
                sheets = sheets.Where(t => t.Submitted <= DateTime.Parse(dateTo));
            }
            if (!string.IsNullOrEmpty(id))
            {
                model.Id = int.Parse(id);
                sheets = sheets.Where(t => t.TimesheetID == int.Parse(id));
            }

            //big ol' switch statement determines how to sort the data in the table
            switch (sortOrder)
            { 
                case "id":
                    sheets = sheets.OrderBy(t => t.TimesheetID);
                    break;
                case "id_desc":
                    sheets = sheets.OrderByDescending(t => t.TimesheetID);
                    break;
                case "pname":
                    sheets = sheets.OrderBy(t => t.ProviderName);
                    break;
                case "pname_desc":
                    sheets = sheets.OrderByDescending(t => t.ProviderName);
                    break;
                case "prime":
                    sheets = sheets.OrderBy(t => t.ClientPrime);
                    break;
                case "prime_desc":
                    sheets = sheets.OrderByDescending(t => t.ClientPrime);
                    break;
                case "cname":
                    sheets = sheets.OrderBy(t => t.ClientName);
                    break;
                case "cname_desc":
                    sheets = sheets.OrderByDescending(t => t.ClientName);
                    break;
                case "date":
                    sheets = sheets.OrderBy(t => t.Submitted);
                    break;
                case "date_desc":
                    sheets = sheets.OrderByDescending(t => t.Submitted);
                    break;
                case "hours":
                    sheets = sheets.OrderBy(t => t.Hours);
                    break;
                case "hours_desc":
                    sheets = sheets.OrderByDescending(t => t.Hours);
                    break;
                case "providerid":
                    sheets = sheets.OrderBy(t => t.ProviderID);
                    break;
                case "providerid_desc":
                    sheets = sheets.OrderByDescending(t => t.ProviderID);
                    break;
                default:
                    sheets = sheets.OrderBy(t => t.TimesheetID);
                    break;
            }

            model.SortOrder = sortOrder;
            model.Sheets = new List<Timesheet>(sheets);
            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private IEnumerable<Timesheet> GetSheets()
        {
            return  _Tcontext.Timesheet.AsEnumerable();
        }

        //should return a Timesheet View
        public async Task<IActionResult> Timesheet(int ID)
        {
            var timesheet =  _Tcontext.Timesheet.Find(ID);
            timesheet.Shifts = new List<Shift>
            {
                new Shift
                {
                    Date = DateTime.Parse("3/11/2020"),
                    In = DateTime.Parse("11:30 AM"),
                    Out = DateTime.Parse("7:30 PM"),
                    Hours = 8.00,
                    Group = false
                },
                new Shift
                {
                    Date = DateTime.Parse("3/12/2020"),
                    In = DateTime.Parse("11:30 AM"),
                    Out = DateTime.Parse("7:30 PM"),
                    Hours = 8.00,
                    Group = false
                }
            };
                
            timesheet.Lock = _Lcontext.LockTableRow.FirstOrDefault(r => r.TimesheetID == ID);

            if (timesheet.Lock != null) return View(timesheet);

            timesheet.Lock = new LockTableRow
                {
                    TimesheetID = ID,
                    LastInteraction = DateTime.Now,
                    TimeLocked = DateTime.Now,
                    User = User.Identity.Name
                };

            _Lcontext.Add(timesheet.Lock);
            await _Lcontext.SaveChangesAsync();

            return View(timesheet);
        }

        public FileContentResult DownloadCSV(string pName, string cName, string dateFrom, string dateTo, string prime, string id)
        {
            var sheets = GetSheets();

            
            //filter the timesheets 
            if (!string.IsNullOrEmpty(pName))
                sheets = sheets.Where(t => t.ProviderName.ToLower().Contains(pName.ToLower()));

            if (!string.IsNullOrEmpty(cName))
                sheets = sheets.Where(t => t.ClientName.ToLower().Contains(cName.ToLower()));

            if (!string.IsNullOrEmpty(dateFrom))
                sheets = sheets.Where(t => t.Submitted >= DateTime.Parse(dateFrom));

            if (!string.IsNullOrEmpty(dateTo))
                sheets = sheets.Where(t => t.Submitted <= DateTime.Parse(dateTo));

            if (!string.IsNullOrEmpty(prime))
                sheets = sheets.Where(t => t.ClientPrime == prime);

            if (!string.IsNullOrEmpty(id))
                sheets = sheets.Where(t => t.TimesheetID == int.Parse(id));

            //the following loops through every property in a timesheet, first saving the names of the properties to 
            //act as a header. Then, it loops through every timesheet, adding every individual property of the timesheet
            //to the csv, then returning it for download.
            var properties = typeof(Timesheet).GetProperties();
            var csv = properties.Aggregate("", (current, f) => current + (f.Name + ','));
            foreach (var s in sheets)
            {
                csv += '\n';
                foreach (var p in properties)
                {
                    
                    if (p.GetValue(s) != null)
                        csv += "\"" + p.GetValue(s).ToString().Replace("\"","\"\"") + "\"";
                    csv += ',';
                }
            }
            var name = "Submissions_summary_" + DateTime.Now.ToString("yyyy-MM-dd_HH:mm:ss") + ".csv";
            return File(new System.Text.UTF8Encoding().GetBytes(csv), "text/csv", name);
        }

    }
}

AdminUI/Controllers/TimesheetController.cs
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AdminUI.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace AdminUI.Controllers
{
    public class TimesheetController : Controller
    {
        private readonly ILogger<TimesheetController> _logger;
        private readonly TimesheetContext _Tcontext;
        private readonly LockTableContext _Lcontext;


        public TimesheetController(ILogger<TimesheetController> logger, TimesheetContext Tcontext,
            LockTableContext Lcontext)
        {
            _Tcontext = Tcontext;
            _Lcontext = Lcontext;
            _logger = logger;
        }

        [HttpPost]
        public async Task<IActionResult> Process(int id, string Status, string RejectionReason)
        {
            var timesheet = await _Tcontext.Timesheet
                .FirstOrDefaultAsync(m => m.TimesheetID == id);
            if (timesheet == null)
                return NotFound();
            var lockRow= await _Lcontext.LockTableRow
                .FirstOrDefaultAsync(m => m.TimesheetID == id);
            //Debug.WriteLine(lockRow.User);
            if (lockRow == null || !lockRow.User.Equals(User.Identity.Name, StringComparison.CurrentCultureIgnoreCase))
                return View("NoPermission");
            timesheet.Status = Status;
            timesheet.RejectionReason = RejectionReason;
            timesheet.AdminActivity = Status + " by " + lockRow.User + " on " + DateTime.Now;
            if (ModelState.IsValid)
            {
                try
                {
                    _Tcontext.Update(timesheet);
                    await _Tcontext.SaveChangesAsync();
                    _Lcontext.Remove(lockRow);
                    await _Lcontext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (!_Tcontext.Timesheet.Any(e => e.TimesheetID == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("Index","Home");
        }
    }
}

AdminUI/Controllers/TimesheetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AdminUI.Data;
using AdminUI.Models;

namespace AdminUI.Controllers
{
    public class TimesheetsController : Controller
    {
        private readonly TimesheetContext _context;

        public TimesheetsController(TimesheetContext context)
        {
            _context = context;
        }

        // GET: Timesheets
        public async Task<IActionResult> Index()
        {
            return View(await _context.Timesheet.ToListAsync());
        }

        // GET: Timesheets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheet
                .FirstOrDefaultAsync(m => m.TimesheetID == id);
            if (timesheet == null)
            {
                return NotFound();
            }

            Console.WriteLine(View(timesheet));
            return View(timesheet);
        }

        // GET: Timesheets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Timesheets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TimesheetID,ClientName,ClientPrime,ProviderName,ProviderID,CMOrg,SCPAName,Service,ModCD,Units,Type,Freq,Hours,ServiceGoal,ProgressNotes,ClientSignature,ClientSigned,ProviderSignature,ProviderSigned,Submitted")] Timesheet timesheet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(timesheet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(timesheet);
        }

        // GET: Timesheets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheet.FindAsync(id);
            if (timesheet == null)
            {
                return NotFound();
            }
            return View(timesheet);
        }

        // POST: Timesheets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TimesheetID,ClientName,ClientPrime,ProviderName,ProviderID,CMOrg,SCPAName,Service,ModCD,Units,Type,Freq,Hours,ServiceGoal,ProgressNotes,ClientSignature,ClientSigned,ProviderSignature,ProviderSigned,Submitted")] Timesheet timesheet)
        {
            if (id != timesheet.TimesheetID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(timesheet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TimesheetExists(timesheet.TimesheetID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(timesheet);
        }


        // GET: Timesheets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var timesheet = await _context.Timesheet
                .FirstOrDefaultAsync(m => m.TimesheetID == id);
            if (timesheet == null)
            {
                return NotFound();
            }

            return View(timesheet);
        }

        // POST: Timesheets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var timesheet = await _context.Timesheet.FindAsync(id);
            _context.Timesheet.Remove(timesheet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TimesheetExists(int id)
        {
            return _context.Timesheet.Any(e => e.TimesheetID == id);
        }
    }
}

AdminUI/Views/Home/Index.cshtml
@using System.Collections
@using Amazon.CodeDeploy
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@model HomeModel
@{
    ViewData["Title"] = "Home Page";

    //Multnomah County Blue and Green
    //var m_blue = "#295F97";
    //var m_green = "#467839";

    //used for zebra print table
    var color = "#8FDDE6";
}
<link rel="manifest" href="~/manifest.json">
<!-- Note: Avoid using inline styles as much as possible. Instead, use classes or ids & .css files -->

<div class="leftnav">
    <p>This space could be use for saved filters, like so:</p>
    <p>@Html.ActionLink("Submitted by Donald Duck", "Index", new {pname="Donald Duck"})</p>
    <p>@Html.ActionLink("Submitted in the last two days", "Index", new {datefrom=@DateTime.Today.AddDays(-2).ToString("yyyy-MM-dd")}) </p>
    <p>@Html.ActionLink("All unprocessed Timesheets", "Index", new { })</p>
    <p>Filters themselves can be down below the saved filters</p>
</div>

<div class="rightnav">
    <p>This space could be used to preview a timesheet instead of opening it up a new tab</p>
    <p>Definitely not a part of the MVP</p>
    <p>Could be a fun stretch goal tho</p>
    <p>Regardless, both sidebars should be collapsible/adjustable</p>
</div>

<div class="text-center" 
     style="background-color: var(--light-grey); width: 100%; margin-top: 0; padding-top: 25px; padding-bottom: 25px;
                                      left: 0; border-radius: 10px;">
    @if (SignInManager.IsSignedIn(User))
    {
        <form>
            <label for="id">ID:</label>
            <input type="number" name="id" id="id" value="@Model.Id"/>

            <label for="pName">Provider Name:</label>
            <input type="text" name="pName" id="pName" value="@Model.PName">

            <label for="pName">Provider ID:</label>
            <input type="text" name="providerId" id="providerId" value="@Model.ProviderId">

            <label for="cName">Client Name:</label>
            <input type="text" name="cName" id="cName" value="@Model.CName">

            <label for="prime">Client Prime:</label>
            <input type="text" name="prime" id="prime" value="@Model.Prime">

            <label for="dateFrom">From:</label>
            <input type="date" name="dateFrom" id="dateFrom" value="@Model.DateFrom">

            <label for="dateTo">To:</label>
            <input type="date" name="dateTo" id="dateTo" value="@Model.DateTo"><br/>

            <input role="button" class="btn btn-primary" type="submit" value="Apply Filters"/>
            @Html.ActionLink("Download CSV", "DownloadCSV", new
            {
                id = Model.Id,
                pname = Model.PName,
                prime = Model.Prime,
                cname = Model.CName,
                datefrom = Model.DateFrom,
                dateto = Model.DateTo,
            }, new
            {
                @class = "btn btn-dark "
            })
            <br/><br/>
        </form>


        <dir id="check-the-css-file">
        <table width="100%">
        <tr class="color-div" style="background-color: #0294B5">
            <!--This ugly block of code can probably be fixed, but I'm not sure how tbh. Right now each 
            HTML ActionLink sorts the data in the table and having 2 sets for each column allows the 
            user to toggle back and forth between descending and ascending-->
            @if (Model.SortOrder == "id")
            {
                <th>@Html.ActionLink("ID", "Index", new
                    {
                        sortOrder = "id_desc",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            else
            {

                <th>@Html.ActionLink("ID", "Index", new
                    {
                        sortOrder = "id",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo

                    })</th>
            }

            @if (Model.SortOrder == "pname")
            {
                <th>@Html.ActionLink("Provider Name", "Index", new
                    {
                        sortOrder = "pname_desc",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo

                    })</th>
            }
            else
            {
                <th>@Html.ActionLink("Provider Name", "Index", new
                    {
                        sortOrder = "pname",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo

                    })</th>
            }
            @if (Model.SortOrder == "providerid")
            {
                <th>@Html.ActionLink("Provider ID", "Index", new
                    {
                        sortOrder = "providerid_desc",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            else
            {
                <th>@Html.ActionLink("Provider ID", "Index", new
                    {
                        sortOrder = "providerid",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            @if (Model.SortOrder == "cname")
            {
                <th>@Html.ActionLink("Client Name", "Index", new
                    {
                        sortOrder = "cname_desc",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            else
            {

                <th>@Html.ActionLink("Client Name", "Index", new
                    {
                        sortOrder = "cname",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            @if (Model.SortOrder == "prime")
            {
                <th>@Html.ActionLink("Client Prime", "Index", new
                    {
                        sortOrder = "prime_desc",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            else
            {
                <th>@Html.ActionLink("Client Prime", "Index", new
                    {
                        sortOrder = "prime",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            @if (Model.SortOrder == "hours")
            {
                <th>@Html.ActionLink("Hours", "Index", new
                    {
                        sortOrder = "hours_desc",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            else
            {

                <th>@Html.ActionLink("Hours", "Index", new
                    {
                        sortOrder = "hours",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            @if (Model.SortOrder == "date")
            {
                <th>@Html.ActionLink("Date Submitted", "Index", new
                    {
                        sortOrder = "date_desc",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
            else
            {

                <th>@Html.ActionLink("Date Submitted", "Index", new
                    {
                        sortOrder = "date",
                        id = Model.Id,
                        pname = Model.PName,
                        prime = Model.Prime,
                        cname = Model.CName,
                        datefrom = Model.DateFrom,
                        dateto = Model.DateTo
                    })</th>
            }
        </tr>
        @foreach (var t in Model.Sheets)
        {
            {
                //I guess this is how you do zebra print tables in CSHTML? n-thchild CSS doesn't work in IE
                color = color == "#8FDDE6" ? "#E6EFF3" : "#8FDDE6";
            }
            <tr class="color-div" style="background-color: @color">
                <td>@Html.ActionLink(@t.TimesheetID.ToString(), "Timesheet", new {ID = @t.TimesheetID})</td>
                <td>@t.ProviderName</td>
                <td>@t.ProviderID</td>
                <td>@t.ClientName</td>
                <td>@t.ClientPrime</td>
                <td>@t.Hours</td>
                <td>@t.Submitted</td>
            </tr>
        }
        </table>
        @if (Model.Sheets.Count == 0)
        {
            <br/>
            <p>No Timesheets found matching parameters</p>
        }
        </dir>
        <br/>
        <button type="submit">Process selected timesheets</button>
    }else { <h1>Please <a asp-area="Identity" asp-page="/Account/Login">login</a> or <a asp-area="Identity" asp-page="/Account/Register">register</a> to continue</h1>}
</div>